version: '2'

services:
  syphon-telegram:
    image: syphon-telegram
    container_name: syphon_telegram
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always