using Syphon.Parsing;
using Syphon.Processing;
    
namespace Syphon.Configuration
{
    internal sealed class CaptainRuPreset : IPreset
    {
        public string Id => "captain-ru";

        public string Name => "Капитан дальнего плавания";

        public string[] Boundaries { get; } = new[]
        {
            " ", 
            "\n    ", 
            ".", 
            ",", 
            "-", 
            "—", 
            ":", 
            "!", 
            "?", 
        };

        public IParser[] Parsers { get; } = new IParser[]
        {
            new Punctuation(new string[] {
            }),
            new Verb(new string[] {
                "(?<end>(ил|ал|ась|ала|ало|али)\\b)", 
                "(?<end>(ат|или|ут|ыл|ыло|ыли|ыла)\\b)", 
                "(?<end>(ать|ить|еть|аться|еться|иться|ул|ил|ал|ула|ала|ила|улся|ился|ался|илась|алась|иться|улась|ило|ало|уло|илось|алось|улось)\\b)", 
            }),
            new Noun(new string[] {
                "(?<end>(ант|ин|ец|да|ер|ка|ок|зь|акт|ис|ор|ик|та|ул|он|ид|ри|уй|инг)\\b)", 
                "(?<end>(ма|чи|ча|че|чь|ну|ын|ына|ыни|ыно|от|ня|ди|ги|ра)\\b)", 
            }),
            new Adjective(new string[] {
                "[^\\b](?<end>(ый|ий|ай|ое|ие|ого|его|их|им|ом|ой|ых|ую|ая|уя)\\b)", 
                "[^\\b](?<end>(ый|ий|ай|ей|ой|ее|его|ого|им|ая|ия|ыя|оя|ому|ыми|ими|ым)\\b)", 
                "[^\\b](?<end>(его|ые|ии|ие)\\b)", 
            }),
            new Preposition(new string[] {
                "(?<end>\\b(и|в|на|от|под|за|как|что|со|или|у|но|из|за|под|к|для|до|после|без|можно|же|по|)\\b)", 
            }),
        };


        public IRule[] Rules { get; } = new IRule[]
        {
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Whitespace,
                Propability = 128,
                IgnoreWhitespaces = true,
                KillPreviousWhitespace = true,
                RequiresAi = false,
                Templates = new string[] {
                    ", ебать меня якорем в анус, ",
                    ", якорь мне в жопу, ",
                    ", ядерный запас мне в рот, ",
                    ", автомат мне в анал, ",
                    ", пулемет мне в рыло, ",
                    ", ебать меня ракетницей, ",
                    ", отъебать вас гранатой, ",
                    ", линкор те в жопу, ",
                    ", отсоси-ка хуй морского волка, ",
                    ", ебать тя тамбовским волком, ",
                    ", срать мне на палубу, ",
                    ", ссать мне в подзорную трубу, ",
                    ", ебать моих корабельных крыс, ",
                    ", дрочить моим корабельным блядям, ",
                    ", ебать моих матросов, ",
                    ", парус мне на хуй, ",
                    ", ебал я корабельные двигатели, ",
                    ", отъеберить тя в трюме, ",
                    ", трос мне в анус, ",
                    ", мачту мне в рот, ",
                    ", жопа с парусами, ",
                    ", отсосите у меня тысяча матросов, ",
                    ", тысяча блядей, ",
                    " - обосрать мои белые паруса - ",
                    " - отъебать всех нах в кубрике - ",
                    " - ссал я на всё с высоты мачты - ",
                    " - винт мне в жопу против часовой стрелки - ",
                    " - сеть со скумбрией тебе в пизду - ",
                    " - клад мне в рот - ",
                    " - ебать моего попугая - ",
                    " - наглазную повязку мне в анал - ",
                    " - десятимильный мой хуй - ",
                    " - отдать швартовые в жопу - ",
                    " - поднять бля якоря - ",
                    " - разъебись оно всё торпедой - ",
                    " - катамаран мне в очко - ",
                    " - свисток мне в жопу по самое ухо - ",
                    " - наебериться ромом на тыщу дней - ",
                    " - закрутить те хуй морским узлом - ",
                    " - вали нахуй с моего корабля - ",
                    " - ебать тебя шваброй по-флотски - ",
                    " - отсоси моё загорелое очко - ",
                    ", мудоблядский перископ, ",
                    ", ебать моего стармеха, ",
                    ", пизда под килем, ",
                    ", ебать мои необитаемые острова, ",
                    ", срать мне на палубу, ",
                    ", изговнять мой трюм, ",
                    ", ебать мои сокровища, ",
                    ", отпиздить мою команду, ",
                    ", штурвал мне в зад, ",
                    ", сто узлов мне на хуй, ",
                    ", смазать мою жопу машинным маслом, ",
                    ", шторм мне в глотку, ",
                    ", ебать мою турбину, ",
                    ", соляр мне в анус, ",
                    ", насадить меня на выхлопную трубу, ",
                    ", сто миль ебли, ",
                    ", ебать тебя штурвалом в очко, ",
                    ", полный сука вперёд, ",
                    ", блядь ты корабельная, ",
                    ", отъебать тебя на корме, ",
                    ", штиль мне в пизду, ",
                    ", отъебать моего кока, ",
                    ", задуть тебе бризом в анал, ",
                },
                SpecificWords = new string[] {
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                    TokenType.Noun,
                    TokenType.Verb,
                    TokenType.Adjective,
                },
                NotAfter = new TokenType[] {
                },
            }),
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Dot,
                Propability = 64,
                IgnoreWhitespaces = false,
                KillPreviousWhitespace = false,
                RequiresAi = false,
                Templates = new string[] {
                    ". В общем, отсосите-ка хуйку!",
                    ". Мудоёбщина, прошу прощения!",
                    ". И срать на всё бытие!",
                    ". К слову, пойду я опорожню анус...",
                    ". Но это, бля, всё хуйня, как сказал бы неприличный человек!",
                    ". Блядь, пиздец просто полнейший, Вы тоже так считаете?",
                    ". Охуеннейше!",
                    ". Препиздостно!",
                    ". Это типичная точка зрения пидорасов.",
                },
                SpecificWords = new string[] {
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                },
                NotAfter = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
            }),
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Question,
                Propability = 128,
                IgnoreWhitespaces = false,
                KillPreviousWhitespace = false,
                RequiresAi = false,
                Templates = new string[] {
                    "? Ебануть тебя моим кортиком!",
                    "? Тельняшку тебе в пизду!",
                    "? Срал я на тебя пушечными ядрами.",
                    "? Для ебаного капитана это хуевый вопрос...",
                    "? В пизду мою пристань...",
                    ", трап те в жопу?",
                    ", тупая ты крыса?",
                    ", палубный пидор?",
                    ", штормовая сучара?",
                    "? Деревянную ногу тебе во влагалище.",
                    "? Шляпу капитана тебе в пиздень!",
                },
                SpecificWords = new string[] {
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                },
                NotAfter = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
            }),
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Whitespace,
                Propability = 128,
                IgnoreWhitespaces = true,
                KillPreviousWhitespace = true,
                RequiresAi = true,
                Templates = new string[] {
                    ", ебать меня {noun:Ablative} в анус, ",
                    ", {noun:Genitive} мне в жопу, ",
                    ", ядерный {noun} мне в рот, ",
                    ", {noun:Genitive} мне в анал, ",
                    ", {noun:Genitive} мне в рыло, ",
                    ", ебать меня {noun:Ablative}, ",
                    ", отъебать вас {noun:Ablative}, ",
                    ", {noun} те в жопу, ",
                    ", отсоси-ка хуй морского {noun:Accusative}, ",
                    ", ебать тебя тамбовским {noun:Ablative}, ",
                    ", срать мне на {noun:Accusative}, ",
                    ", {noun:Genitive} мне на хуй, ",
                    ", {noun:Genitive} мне в анус, ",
                    ", {noun:Genitive} мне в рот, ",
                    ", {noun:Genitive} с парусами, ",
                    " - отъебать всех нахуй в {noun:Prepositional} - ",
                    " - ссал я на всё с высоты {noun:Genitive}- ",
                    " - {noun} мне в жопу против часовой стрелки - ",
                    " - {noun:Accusative} со скумбрией тебе в пизду - ",
                    " - {noun:Accusative} мне в рот - ",
                    " - ебать моего {noun:Accusative} - ",
                    " - десятимильный мой хуй - ",
                    " - отдать швартовые в {noun:Prepositional} - ",
                    " - разъебись оно всё {noun:Ablative} - ",
                    " - {noun:Accusative} мне в очко - ",
                    " - {noun:Accusative} мне в жопу по самое ухо - ",
                    " - наебериться {noun:Ablative} на тыщу дней - ",
                    ", мудоблядский {noun}, ",
                    ", ебать моего {noun:Genitive}, ",
                    ", {noun} под килем, ",
                    ", {noun:Accusative} мне в зад, ",
                    ", ебать тебя {noun:Ablative} в очко, ",
                    ", {noun} ты корабельный, ",
                    ", {noun:Accusative} мне в пизду, ",
                    ", отъебать моего {noun:Genitive}, ",
                    ", задуть тебе {noun:Ablative} в анал, ",
                },
                SpecificWords = new string[] {
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                    TokenType.Noun,
                    TokenType.Verb,
                    TokenType.Adjective,
                },
                NotAfter = new TokenType[] {
                },
            }),
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Dot,
                Propability = 64,
                IgnoreWhitespaces = false,
                KillPreviousWhitespace = false,
                RequiresAi = true,
                Templates = new string[] {
                    ". В общем, отсосите-ка у {noun:Genitive(1)}!",
                    ", {noun}, прошу прощения!",
                    ". К слову, пойду я насру на {noun:Genitive}...",
                    ". Но это, бля, всё хуйня, как сказал бы {noun}!",
                    ". Блядь, {noun} просто полнейший, Вы тоже так считаете?",
                    ". Это типичная точка зрения {noun:Accusative}.",
                },
                SpecificWords = new string[] {
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                },
                NotAfter = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
            }),
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Question,
                Propability = 128,
                IgnoreWhitespaces = false,
                KillPreviousWhitespace = false,
                RequiresAi = true,
                Templates = new string[] {
                    "? Ебануть тебя моим {noun:Ablative}!",
                    "? Срал я на тебя {noun:Ablative}.",
                    "? Для ебаного {noun:Accusative} это хуевый вопрос...",
                    ", тупой ты {noun}?",
                    ", палубный {noun}?",
                    ", штормовой {noun}?",
                    "? Деревянный {noun} тебе во влагалище.",
                    "? Шляпу {noun:Genitive} тебе в пиздень!",
                },
                SpecificWords = new string[] {
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                },
                NotAfter = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
            }),
        };


        public IWordBuilder WordBuilder { get; } = new WordBuilder(
            new string[]
            {
                "пидор",
                "муд",
                "хуе",
                "манд",
                "уеб",
                "зл",
                "пизд",
                "говн",
                "перд",
                "ослоеб",
                "говноеб",
                "еб",
                "жоп",
                "выеб",
            },
            new (string, Cases)[]
            {
                ("ас", Cases.Nominative),
                ("ан", Cases.Nominative),
                ("ос", Cases.Nominative),
                ("охуй", Cases.Nominative),
                ("аса", Cases.Genitive),
                ("ана", Cases.Genitive),
                ("оса", Cases.Genitive),
                ("охуя", Cases.Genitive),
                ("асу", Cases.Dative),
                ("ану", Cases.Dative),
                ("осу", Cases.Dative),
                ("охую", Cases.Dative),
                ("аса", Cases.Accusative),
                ("ана", Cases.Accusative),
                ("оса", Cases.Accusative),
                ("охуя", Cases.Accusative),
                ("асом", Cases.Ablative),
                ("аном", Cases.Ablative),
                ("осом", Cases.Ablative),
                ("охуем", Cases.Ablative),
                ("асе", Cases.Prepositional),
                ("ане", Cases.Prepositional),
                ("осе", Cases.Prepositional),
                ("охуе", Cases.Prepositional),
            });

    }
}
    
