using Syphon.Parsing;
using Syphon.Processing;
    
namespace Syphon.Configuration
{
    internal sealed class JointRuPreset : IPreset
    {
        public string Id => "joint-ru";

        public string Name => "Общий лексикон";

        public string[] Boundaries { get; } = new[]
        {
            " ", 
            "\n    ", 
            ".", 
            ",", 
            "-", 
            "—", 
            ":", 
            "!", 
            "?", 
        };

        public IParser[] Parsers { get; } = new IParser[]
        {
            new Punctuation(new string[] {
            }),
            new Verb(new string[] {
                "(?<end>(ил|ал|ась|ала|ало|али)\\b)", 
                "(?<end>(ат|или|ут|ыл|ыло|ыли|ыла)\\b)", 
                "(?<end>(ать|ить|еть|аться|еться|иться|ул|ил|ал|ула|ала|ила|улся|ился|ался|илась|алась|иться|улась|ило|ало|уло|илось|алось|улось)\\b)", 
            }),
            new Noun(new string[] {
                "(?<end>(ант|ин|ец|да|ер|ка|ок|зь|акт|ис|ор|ик|та|ул|он|ид|ри|уй|инг)\\b)", 
                "(?<end>(ма|чи|ча|че|чь|ну|ын|ына|ыни|ыно|от|ня|ди|ги|ра)\\b)", 
            }),
            new Adjective(new string[] {
                "[^\\b](?<end>(ый|ий|ай|ое|ие|ого|его|их|им|ом|ой|ых|ую|ая|уя)\\b)", 
                "[^\\b](?<end>(ый|ий|ай|ей|ой|ее|его|ого|им|ая|ия|ыя|оя|ому|ыми|ими|ым)\\b)", 
                "[^\\b](?<end>(его|ые|ии|ие)\\b)", 
            }),
            new Preposition(new string[] {
                "(?<end>\\b(и|в|на|от|под|за|как|что|со|или|у|но|из|за|под|к|для|до|после|без|можно|же|по|)\\b)", 
            }),
        };


        public IRule[] Rules { get; } = new IRule[]
        {
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Adjective,
                Propability = 64,
                IgnoreWhitespaces = false,
                KillPreviousWhitespace = false,
                RequiresAi = false,
                Templates = new string[] {
                    "* ебан~",
                    "* древн~",
                    "* как пизда ",
                    "*, что мой хуй, ",
                    "* словно хуй ",
                    "* как говно ",
                    "* сияющ~ как мой хуй ",
                    "* ебан~",
                    "* огромн~ как мои яйцы ",
                    "* будто херня ",
                    "*, ссучен~ с хуями ",
                    "* ссан~",
                    "*, задрочен~ как хуета, ",
                    "* ссучен~",
                    "* ссучен~",
                    "* злоебан~",
                    "*-ебан~",
                    "*-злоебан~",
                    "* дрочен~",
                    "*-дрочен~",
                    "*-ссан~",
                    "* пидорск~",
                    "*-пидорск~",
                    "* блядск~",
                    "*-блядск~",
                    "* жопн~",
                    "*-жопн~",
                    "* хуев~",
                    "*-хуев~",
                    "* ебан~",
                    "* морск~",
                    "* как штурвал ",
                    "*, что мой киль, ",
                    "* словно чайка в жопе ",
                    "* как говно чайки ",
                    "* сияющ~ как начищенный хуй старого морского волка ",
                    "* огромн~ как мои морские яйцы ",
                    "* будто чайка в жопе ",
                    "*, ссучен~ с морскими хуями ",
                    "* ссан~",
                    "*-ссан~",
                    "* пидорск~",
                    "*-пидорск~",
                    "* блядск~",
                    "*-блядск~",
                    "* жопн~",
                    "*-жопн~",
                    "* хуев~",
                    "*-хуев~",
                    "* штормов~",
                    "*-штормов~",
                },
                SpecificWords = new string[] {
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                },
                After = new TokenType[] {
                },
                NotAfter = new TokenType[] {
                },
            }),
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Whitespace,
                Propability = 128,
                IgnoreWhitespaces = true,
                KillPreviousWhitespace = true,
                RequiresAi = false,
                Templates = new string[] {
                    ", ебать меня якорем в анус, ",
                    ", якорь мне в жопу, ",
                    ", ядерный запас мне в рот, ",
                    ", автомат мне в анал, ",
                    ", пулемет мне в рыло, ",
                    ", ебать меня ракетницей, ",
                    ", отъебать вас гранатой, ",
                    ", линкор те в жопу, ",
                    ", отсоси-ка хуй морского волка, ",
                    ", ебать тя тамбовским волком, ",
                    ", срать мне на палубу, ",
                    ", ссать мне в подзорную трубу, ",
                    ", ебать моих корабельных крыс, ",
                    ", дрочить моим корабельным блядям, ",
                    ", ебать моих матросов, ",
                    ", парус мне на хуй, ",
                    ", ебал я корабельные двигатели, ",
                    ", отъеберить тя в трюме, ",
                    ", трос мне в анус, ",
                    ", мачту мне в рот, ",
                    ", жопа с парусами, ",
                    ", отсосите у меня тысяча матросов, ",
                    ", тысяча блядей, ",
                    " - обосрать мои белые паруса - ",
                    " - отъебать всех нах в кубрике - ",
                    " - ссал я на всё с высоты мачты - ",
                    " - винт мне в жопу против часовой стрелки - ",
                    " - сеть со скумбрией тебе в пизду - ",
                    " - клад мне в рот - ",
                    " - ебать моего попугая - ",
                    " - наглазную повязку мне в анал - ",
                    " - десятимильный мой хуй - ",
                    " - отдать швартовые в жопу - ",
                    " - поднять бля якоря - ",
                    " - разъебись оно всё торпедой - ",
                    " - катамаран мне в очко - ",
                    " - свисток мне в жопу по самое ухо - ",
                    " - наебериться ромом на тыщу дней - ",
                    " - закрутить те хуй морским узлом - ",
                    " - вали нахуй с моего корабля - ",
                    " - ебать тебя шваброй по-флотски - ",
                    " - отсоси моё загорелое очко - ",
                    ", мудоблядский перископ, ",
                    ", ебать моего стармеха, ",
                    ", пизда под килем, ",
                    ", ебать мои необитаемые острова, ",
                    ", срать мне на палубу, ",
                    ", изговнять мой трюм, ",
                    ", ебать мои сокровища, ",
                    ", отпиздить мою команду, ",
                    ", штурвал мне в зад, ",
                    ", сто узлов мне на хуй, ",
                    ", смазать мою жопу машинным маслом, ",
                    ", шторм мне в глотку, ",
                    ", ебать мою турбину, ",
                    ", соляр мне в анус, ",
                    ", насадить меня на выхлопную трубу, ",
                    ", сто миль ебли, ",
                    ", ебать тебя штурвалом в очко, ",
                    ", полный сука вперёд, ",
                    ", блядь ты корабельная, ",
                    ", отъебать тебя на корме, ",
                    ", штиль мне в пизду, ",
                    ", отъебать моего кока, ",
                    ", задуть тебе бризом в анал, ",
                    ", сладкая моя сперма, ",
                    ", ебать меня в анусик, ",
                    ", отсосать мой сладкий хуй, ",
                    ", ебать тебя в попку, ",
                    " ,трахать меня в анус, ",
                    ", дрочить мои эрогенные зоны, ",
                    ", всосать мои яйца, ",
                    ", засадить тебе в жопу, ",
                    ", вставить тебе хуй в анал, ",
                    ", это просто анальная мастурбация, ",
                    ", отавтофеллируйся, ",
                    ", высосать говно из жопы, ",
                    ", клизму мне в анус, ",
                    ", яйца мне в попку, ",
                    ", лизать голову моего хуя, ",
                    ", сглотнуть сладкую жидкость нах, ",
                    ", обстричь мои анальные волосы, ",
                    ", порвать твой анус, ",
                    ", заткнуть мне жопу, ",
                    ", расхуярить твою толстую кишку, ",
                    ", отъеберить твою попку, ",
                    " - и это сладостное долбоёбство - ",
                    " - трахнуть тебя нахуй - ",
                    " - скушай мои сраки - ",
                    " - иметь меня шваброй в жопу - ",
                    " - облизать мои шоколадные яйца - ",
                    " - вылизать твои соски - ",
                    " - вставить тебе хуй в попку - ",
                    " - отсосать хуй и сплюнуть просто - ",
                    " - срать мне на мошонку - ",
                    " - ебать мои яички - ",
                    " - и тут сжимаются мышцы моего анала - ",
                    " - и говно из жопы так и прёт - ",
                    " - анальная сладость нарастает - ",
                    " - кончи же мне в попку - ",
                    " - выеби же меня, самец - ",
                    " - ебать меня в анал - ",
                    " - а я люблю блядунов-шалунишек - ",
                    " - ебать тебя в анальное отверстие - ",
                    ", ебать мою анальную целку, ",
                    ", всадить тебе хуй по самый аппендикс, ",
                    ", блядством это является гейским, ",
                    ", пидарасье, ",
                    ", ебать мой анус, ",
                    ", сапоги мне в жопу, ",
                    ", вазелин мне на хуй, ",
                    ", ебать тебя в анал, ",
                    ", анальная моя сила, ",
                    ", кончать сука мне на соски, ",
                    ", обосраный мой пупочек, ",
                    ", отлизать мою голову хуя, ",
                    ", а вагину в пизду, ",
                    ", анусы рулят, ",
                    ", уебериться по самое немогу через попку, ",
                    ", сучьи кишечные внутренности, ",
                    ", обонанироваться можно, ",
                    ", уебериться до раздражения ануса, ",
                    ", анальная блядь, ",
                    ", ебаный в рот и в анал, ",
                    ", накакать на хуй и на соски, ",
                    ", охуеть вполне вероятно, ",
                    ", ебливый ты пидар, ",
                    ", промудоблядовщина, ",
                    ", отъеберенностное состояние, ",
                    ", охуерический восторг, ",
                    ", уеберенностность, ",
                    ", блядство чистой воды, ",
                    ", выебанность на сто процентов, ",
                    ", заеберская моя империя, ",
                    ", клавиатуру мне во влагалище, ",
                    ", лизать мои эрогенные зоны, ",
                    ", коллайдер мне в жопу, ",
                    ", будь мой анус неладен, ",
                    ", отдефлорировать Ваши отверстия, ",
                    ", зажать в тиски Ваши соски, ",
                    ", выебать ваши отверстия, ",
                    ", обхуяриться как следует алкоголем, ",
                    ", отъеберить сотню самок, ",
                    ", снять тысячу блядей, ",
                    ", поглотить меня пиздой, ",
                    ", блядун мой ненасытный, ",
                    ", взять в полость рта головку хуя, ",
                    ", изхуярить неверных, ",
                    ", перенаправить Вас в пизду, ",
                    ", отонанировать мой хуй, ",
                    ", отмастурбировать Ваше очко, ",
                    ", разъеберить всё до коллапса, ",
                    ", уебениться до потери кровеносного давления, ",
                    " - и это естественно долбоёбство - ",
                    " - отпиздить Вас нахуй - ",
                    " - ссать и срать фекалиями - ",
                    " - уеберская рифма хореем - ",
                    " - охуевшая нынче молодёжь - ",
                    " - криптологию Вам в анус - ",
                    " - ебал я непрерывное кольцо - ",
                    " - срал я на глобальное потепление - ",
                    " - не сдержаться и насрать - ",
                    " - ебать мои яички - ",
                    " - прошу прощения, хуета это - ",
                    " - наебаться отличным виски - ",
                    " - модульный мой пиздоратор - ",
                    " - дифференциальное ебать уравнение - ",
                    " - однополо выебанная особь - ",
                    " - ебать этих пчёл-хуегрызов - ",
                    " - а Вы тоже охуенный блядун - ",
                    " - ебать Вас в анальное отверстие - ",
                    ", ебать Вашу целку, ",
                    ", всадить вам хуй по самый желудок, ",
                    ", блядством это является, ",
                    ", как говорится, пидарасье, ",
                    ", ебать тысячу анусов, ",
                    ", охуеть возможно от этого, ",
                    ", ебанавтика, ",
                    ", ебать всё население в анал, ",
                    ", невъебическая сила, ",
                    ", ебать мою диссертацию, ",
                    ", обосраный пуловер, ",
                    ", ебучая вагина, ",
                    ", ебать Ваше вагинальное отверстие, ",
                    ", ебаная лошадка, ",
                    ", уеберить Вас по самое немогу, ",
                    ", сучьи внутренности, ",
                    ", обонанироваться можно, ",
                    ", уебериться, ",
                    ", блядь, ",
                    ", ебаный в рот и в анал, ",
                    ", накакать на хуй и в пизду, ",
                    ", охуеть вполне вероятно, ",
                    ", ебливый Вы наш, ",
                    ", ебать я всё хочу, ",
                    ", руку мне в жопу, ",
                    ", хуй мне в пупок, ",
                    ", залупу мне в нос, ",
                    ", отъеберить всех как следует, ",
                    ", еба, ",
                    ", разорвать тебе анус, ",
                    ", якорь мне в жопу, ",
                    ", пиздееееец, ",
                    ", ёпт, ",
                    ", вот бля, ",
                    ", ебана, ",
                    ", пердануть тебе в нос, ",
                    ", насрать тебе в ухо, ",
                    ", зашить твой анус, ",
                    ", ебать вас в жопу, ",
                    ", просто злоебенище, ",
                    ", уебаться просто, ",
                    ", еба, ",
                    ", дремучая пиздень, ",
                    ", вот говно, ",
                    ", срать на всех, ",
                    ", обдристаться можно, ",
                    ", ебать-копать, ",
                    ", фак мой моск, ",
                    ", вротмненоги, ",
                    ", блядь, ",
                    ", нахуй, ",
                    ", ебанаврот, ",
                    ", в жопу, ",
                    " - и это просто пиздец - долбоёбство просто - ",
                    " - уебанство - ",
                    " - иметь тебя в рот и в жопу - ",
                    " - разъеберище полное - ",
                    " - отпиздить всех нахуй - ",
                    " - ссать и срать - ",
                    " - и разъебись оно всё к чертям сучьим - ",
                    " - ебаный конём в рот и в жопу - ",
                    " - вот еба - ",
                    " - усраться просто - ",
                    " - отлижите клитор или отсосите хуй, неважно - ",
                    " - а обычно пиздец быстро приходит - ",
                    " - жопа поглотит вас - ",
                    " - наступает пиздец - ",
                    " - разъебенить всё - ",
                    " - ух, ядрёная была ебля - ",
                    " - насрать мне на рыло - ",
                    " - разодрать вам пизду - ",
                    " - лизать мою мошонку - ",
                    " - ебать ваши яйца - ",
                    " - драть вас в жопу - ",
                    " - лизать моё шоколадное очко - ",
                    " - вот тут полный пиздец - ",
                    " - и как же тут не охуеть - ",
                    " - драть вас шваброй в жопу - ",
                    " - но это ж пиздец! - ",
                    " - и кто бы блядь подумал - ",
                    " - ебать его в рот - ",
                    ", ебалайка сучья, ",
                    ", трахать вас и спереди и сзади, ",
                    ", въебать бы тебя в стену, ",
                    ", ебать-колотить, ",
                    ", отпиздить всех нах, ",
                    ", лизать моё очко, ",
                    ", сосать мой хуй, ",
                    ", нюхни моего пердежа, ",
                    ", выпей-ка моих ссак, ",
                    ", сожри кучу говна, ",
                    ", намазать тебе хуй ядом, ",
                    ", нассать на лоб тебе, ",
                    ", ебать тебя во все отверстия, ",
                    ", и это бздунство, ",
                    ", блядина, ",
                    ", пидарас, ",
                    ", бздеть на всё, ",
                    ", ебать сто коров, ",
                    ", охуеть просто, ",
                    ", охуенно просто, ",
                    ", ебанавт, ",
                    ", ебать вас всех, ",
                    ", оттолкать говно в жопе, ",
                    ", срать я хотел на всё, ",
                    ", обоссаться просто, ",
                    ", обоссаный валенок, ",
                    ", ебучая пиздопроёбина, ",
                    ", продраная жопа, ",
                    ", ебать вас в анус, ",
                    ", рвать тебе целку, ",
                    ", сучий мудозвон, ",
                    ", сука ебаная, ",
                    ", сучий потрох, ",
                    ", обдрочиться просто, ",
                    ", срать тебе в рот, ",
                    ", бля, ",
                    ", ебаный в рот, ",
                    ", обосраться, ",
                    ", охуеть можно, ",
                    ", и хватит тут блядовать, ",
                    ", и это пиздец блядство, ",
                    ", впиздячить те по уши, ",
                    ", дуроёб, ",
                    ", ебическая сила, ",
                    ", коноёб, ",
                    ", однохуйственно, ",
                    ", пизда малосольная, ",
                    ", пиздун, ",
                    ", хуеглот, ",
                    ", хуё-моё, ",
                    ", шобла-ёбла, ",
                    ", блядь, ",
                    ", нахуй, ",
                    ", говно с глазами, ",
                    ", хуй тебе в рот, ",
                    ", в рот мне ноги, ",
                    ", вот пиздец, ",
                    ", ебаный в рот, ",
                    ", хули, ",
                    ", ебаный папуас, ",
                    ", бля, ",
                    ", сучье вымя, ",
                    ", блядина, ",
                    ", хуев внук, ",
                    ", пидарасов сын, ",
                    ", гомосяцкое отродье, ",
                    ", ебать сто блядей, ",
                    ", артефакт мне на хуй, *",
                    ", хуй тебе на лоб, ",
                    ", пизду тебе на нос, ",
                    ", пидор, ",
                    ", кошак ебучий, ",
                    ", тварь злоебанная, ",
                    ", мастурбируя, ",
                    ", дроча на старых ебливых бабуль, ",
                    ", отсасывая у самого себя, ",
                    ", оебинеть в корягу, ",
                    ", вот говно, ",
                    ", пиздец, ",
                    ", еб твою мать, ",
                    ", надеть на хуй артефакт, ",
                    ", говно с глазами, ",
                    ", хуй тебе в рот, ",
                    ", пидорье отродье, ",
                    ", чтоб тебе хуй оторвало, ",
                    ", ебаться в рот, ",
                    ", дрочить моему коту, ",
                    ", посасывая хуй как леденец, ",
                    ", но ведь это же пиздец, ",
                    ", товарищи, ",
                    ", в рот мне тороид, ",
                    ", жопки алые, ",
                    ", розовый писюн, ",
                    ", говнючье, ",
                    ", посасывая хуище с яйцами, ",
                    ", ебать тебя, ",
                    ", ебать тебя в рот, ",
                    ", хуй тебе на лоб, ",
                    ", пиздоболоид ебучий, ",
                    ", водопровод тебе в жопу, ",
                    ", перфоратор тебе в сраку, ",
                    ", сосать мои колбасы, ",
                    ", мастурбировать мне хуй, ",
                    ", полируя говно, ",
                    ", пиздец одуванчику, ",
                    ", хуйня ебаная, ",
                    ", обосраться тебе на голову, ",
                    ", ебаный в рот, ",
                    ", сука ебаная, ",
                    ", надеть на хуй артефакт, ",
                    ", блядь, ",
                    ", нахуй, ",
                    ", морское говно с глазами, ",
                    ", парус тебе в рот, ",
                    ", вот пиздец, ",
                    ", ебаный в рот, ",
                    ", хули, ",
                    ", ебаный папуас, ",
                    ", бля, ",
                    ", сучий парус, ",
                    ", морская блядина, ",
                    ", ебаный внук морской рыбы-хуй, ",
                    ", рыбий сын, ",
                    ", папуасское отродье, ",
                    ", ебать сто матросов, ",
                    ", штурвал мне на хуй, *",
                    ", хуй тебе на корму, ",
                    ", пизду тебе на матчу, ",
                    ", пидор, ",
                    ", матрос ебучий, ",
                    ", каракатица злоебанная, ",
                    ", мастурбируя хуй старого морского волка, ",
                    ", вот говно, ",
                    ", пиздец, ",
                    ", еб твою мать, ",
                    ", надеть на хуй штурвал, ",
                    ", говно с парусом, ",
                    ", хуй тебе в грот, ",
                    ", пидорье отродье, ",
                    ", чтоб тебе хуй оторвало, ",
                    ", ебаться в рот, ",
                    ", дрочить моему корабельному коту, ",
                    ", посасывая хуй как леденец, ",
                    ", но ведь это же пиздец, ",
                    ", матросы, ",
                    ", в рот мне пушку, ",
                    ", ебать тебя в рот, ",
                    ", хуй тебе на парус, ",
                    ", штурвал тебе в жопу, ",
                    ", парус тебе в сраку, ",
                    ", сосать мой морской хуй, ",
                    ", мастурбировать мне хуй, ",
                    ", ебаный в рот, ",
                    ", сука ебаная, ",
                    ", надеть на хуй штурвал, ",
                },
                SpecificWords = new string[] {
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                    TokenType.Noun,
                    TokenType.Verb,
                    TokenType.Adjective,
                },
                NotAfter = new TokenType[] {
                },
            }),
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Preposition,
                Propability = 128,
                IgnoreWhitespaces = false,
                KillPreviousWhitespace = false,
                RequiresAi = false,
                Templates = new string[] {
                    "ни разу не",
                    "вообще не",
                    "вот пиздец, вообще не",
                    "нихуя не",
                    "даже не немного, а вообще нихуя не",
                    ", бля, ну бля, ну вот совсем нихуя нисколечко не",
                    "нихуя, ну вот совсем нихуя не",
                },
                SpecificWords = new string[] {
                    "не",
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                },
                NotAfter = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
            }),
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Preposition,
                Propability = 128,
                IgnoreWhitespaces = false,
                KillPreviousWhitespace = false,
                RequiresAi = false,
                Templates = new string[] {
                    "но, хули,",
                    "но, блядь,",
                    "но, бля,",
                    "но, ебаный в рот,",
                },
                SpecificWords = new string[] {
                    "но",
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                },
                NotAfter = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
            }),
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Preposition,
                Propability = 128,
                IgnoreWhitespaces = false,
                KillPreviousWhitespace = false,
                RequiresAi = false,
                Templates = new string[] {
                    "в рот и в",
                    "в говно и в",
                    "в жопу и в",
                    "в пизду и в",
                    "в корму и в",
                    "в рот и в",
                    "в говно и в",
                    "в жопу и в",
                    "в пизду и в",
                    "в пиздак и в",
                },
                SpecificWords = new string[] {
                    "в",
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                },
                NotAfter = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
            }),
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Preposition,
                Propability = 128,
                IgnoreWhitespaces = false,
                KillPreviousWhitespace = false,
                RequiresAi = false,
                Templates = new string[] {
                    "с говном и с",
                    "с хуями, с",
                    ", сука, с",
                },
                SpecificWords = new string[] {
                    "с",
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                },
                NotAfter = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
            }),
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Preposition,
                Propability = 128,
                IgnoreWhitespaces = false,
                KillPreviousWhitespace = false,
                RequiresAi = false,
                Templates = new string[] {
                    "*, хули там,",
                    "* прямо на хуй",
                    "*, с какого-то хуя,",
                    "* с хуями",
                    "*, хули же,",
                    "*, пиздец,",
                },
                SpecificWords = new string[] {
                    "а",
                    "и",
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                },
                NotAfter = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
            }),
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Preposition,
                Propability = 128,
                IgnoreWhitespaces = false,
                KillPreviousWhitespace = false,
                RequiresAi = false,
                Templates = new string[] {
                    "из жопы и",
                    "из говна и",
                },
                SpecificWords = new string[] {
                    "из",
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                },
                NotAfter = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
            }),
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Preposition,
                Propability = 128,
                IgnoreWhitespaces = false,
                KillPreviousWhitespace = false,
                RequiresAi = false,
                Templates = new string[] {
                    "как кустом в жопу",
                    "как говном в ухо",
                    "как парусом в жопу",
                    "как штурвалом в жопу",
                    "как говном в ухо",
                },
                SpecificWords = new string[] {
                    "как",
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                },
                NotAfter = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
            }),
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Preposition,
                Propability = 128,
                IgnoreWhitespaces = false,
                KillPreviousWhitespace = false,
                RequiresAi = false,
                Templates = new string[] {
                    "что, говнючее хуйло,",
                    "что, пидорасы сучьи,",
                },
                SpecificWords = new string[] {
                    "что",
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                },
                NotAfter = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
            }),
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Preposition,
                Propability = 128,
                IgnoreWhitespaces = false,
                KillPreviousWhitespace = false,
                RequiresAi = false,
                Templates = new string[] {
                    "нахуй на",
                    "на, ебань тупой,",
                    "на, ни хуя себе,",
                    "на, морской еблан,",
                    "на, хули же,",
                    "на, еблан,",
                },
                SpecificWords = new string[] {
                    "на",
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                },
                NotAfter = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
            }),
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Noun,
                Propability = 128,
                IgnoreWhitespaces = false,
                KillPreviousWhitespace = false,
                RequiresAi = false,
                Templates = new string[] {
                    "*, пидар~, ",
                    "*-пидарас~",
                    "*, гомосек~, ",
                    "* и гомосек~",
                    "*-пидор~",
                    "*-хуесос~",
                    "*-пидарас~",
                    "*-бароеб~",
                    "*-гомосек~",
                    "*-пизд~",
                    "*, говн~,",
                    "*-хуяр~",
                    "*-бабоеб~",
                    "*-пидор~",
                    "*, хуяр~,",
                },
                SpecificWords = new string[] {
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                },
                NotAfter = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
            }),
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Verb,
                Propability = 128,
                IgnoreWhitespaces = false,
                KillPreviousWhitespace = false,
                RequiresAi = false,
                Templates = new string[] {
                    "*, словно трах~ грязные пидорские жопы,",
                    "*, словно трах~ грязные морские жопы,",
                    "*-дроч~",
                    "*-еб~",
                    "*-пизд~",
                    "*-жоп~",
                    "* и еб~",
                    "*, а также жоп~",
                    "*, и пизд~",
                    "*, а также дроч~",
                    "*, и тем более еб~",
                },
                SpecificWords = new string[] {
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                },
                NotAfter = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
            }),
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Dot,
                Propability = 64,
                IgnoreWhitespaces = false,
                KillPreviousWhitespace = false,
                RequiresAi = false,
                Templates = new string[] {
                    ". В общем, отсосите-ка хуйку!",
                    ". Мудоёбщина, прошу прощения!",
                    ". И срать на всё бытие!",
                    ". К слову, пойду я опорожню анус...",
                    ". Но это бля всё хуйня, как сказал бы неприличный человек!",
                    ". Блядь, пиздец просто полнейший, Вы тоже так считаете?",
                    ". Охуеннейше!",
                    ". Препиздостно!",
                    ". Это типичная точка зрения пидорасов.",
                    " . В общем, сосни-ка мой хуй, сладкий!",
                    ". А ты такой пративный, сучка!",
                    ". А вообще, срал я на хуй тебе!",
                    ". К слову, пойду я опорожню анус перед еблей...",
                    ". Но это всё хуйня и не волнует пидаров!",
                    ". Блядь, но это уже анальный пиздец!",
                    ". Охуеннейше, обожаю анальный!",
                    ". Восхитительно в жопу мне вставили!",
                    ". Это типичное мнение пидарков.",
                    ". В общем, отсосите-ка хуйку!",
                    ". Мудоёбщина, прошу прощения!",
                    ". И срать на всё бытие!",
                    ". К слову, пойду я опорожню анус...",
                    ". Но это бля всё хуйня, как сказал бы неприличный человек!",
                    ". Блядь, пиздец просто полнейший, Вы тоже так считаете?",
                    ". Охуеннейше!",
                    ". Препиздостно!",
                    ". Это типичная точка зрения пидорасов.",
                    ". В общем, отсосите-ка хуй!",
                    ". Короче, мудоёбщина полная!",
                    ". И срать на всё это!",
                    ". К слову, пойду-ка я посру...",
                    ". А вы хоть раз засовывали палец в жопу?",
                    ". Но это всё хуйня!",
                    ". Блядь, вот кто бы мог подумать!",
                    ". Это ж охуеть можно!",
                    ". Да ебать нахуй!",
                    ". Пидоры, что ж с них взять!",
                    ", это тебе не хуй дрочить!",
                    ". Ебаный папуас!",
                    ", просто охуеть!",
                    ". Не нравится - идите на хуй.",
                    ". Иди-ка подрочи верблюду, сука.",
                    ". Однако я бы не советовал тебе сосать мой хуй, это опасно для здоровья, можно сильно травануться.",
                    ". Пиздец котенку, пиздец цыпленку, пиздец машине боевой.",
                    ", и пиздец.",
                    ", так-то!",
                    ", словом, заебись хуйня получилась!",
                    ", хотя вообще это всем похуй.",
                    ", хули ж.",
                    ", но ведь это же всем похую.",
                    ", да и насрать.",
                    ". А вот тут какой-то пидор насрал!",
                    ". Развелось тут пидарасов, блядь!",
                    ", это тебе не хуй дрочить!",
                    ". Ебаный папуас!",
                    ", просто охуеть!",
                    ". Не нравится - плывите на хуй.",
                    ". Иди-ка запихни себе в сраку штурвал и нацепи компас на яйцы, сука.",
                    ". Пиздец морским хуям!",
                    ". Пиздец котенку, пиздец цыпленку, пиздец машине боевой.",
                    ", и пиздец.",
                    ", так-то!",
                    ", словом, заебись хуйня получилась!",
                    ", хотя вообще это всем похуй.",
                    ", хули ж.",
                    ", но ведь это же всем похую.",
                    ", да и насрать.",
                    ". А вот тут какой-то пидор насрал!",
                    ". Развелось тут пидарасов, блядь!",
                },
                SpecificWords = new string[] {
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                },
                NotAfter = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
            }),
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Question,
                Propability = 128,
                IgnoreWhitespaces = false,
                KillPreviousWhitespace = false,
                RequiresAi = false,
                Templates = new string[] {
                    "? Ебать Вас спереди и сзади!",
                    "? Удовлетворить Вас анально!",
                    "? Какал я на всю эту хуйню.",
                    "? Еберически сложный вопрос...",
                    "? Пидорски-риторический вопрос...",
                    ", еберко?",
                    ", мудак?",
                    ", педераст?",
                    ", ебанько?",
                    "? Охуенно сложнейший вопрос.",
                    "? Пиздец, но это вопрос нерешаем.",
                    "? Ебаааать вас всех!",
                    "? Вылижите мои шоколадные яйца.",
                    "? А вообще, мне срать.",
                    "? Уебанский вопрос...",
                    "? Как же ответят на этот вопрос долбоёбы?",
                    "? Кстати, есть чё?",
                    ", мудоёб?",
                    ", мудак?",
                    ", пидор?",
                    ", еба?",
                    "? Охуенно сложный вопрос.",
                    "? Пиздец, вопрос нерешаем.",
                    "? Я вот не ебу!",
                    "? Я вот вообще не ебу!",
                    "? Вот тебе задачка, хуй разгадаешь!",
                    "? Я вот хуй его знает...",
                    "? Да хуй его знает!",
                    "? Я вот не знаю, да мне и похуй.",
                    "? Что это за хуйня?",
                    "? С какого это же хуя?",
                    "? Это с какого еще хуя?",
                    "? Что это такое, пиздец какой-то!",
                    "? Я просто хуею!",
                    "? С  хуев ли?",
                    "? Ебать тебя спереди и сзади!",
                    "? Удовлетворить меня анально!",
                    "? Срал я на всю эту хуйню.",
                    "? Анально сложный вопрос...",
                    "? Пидорский вопрос...",
                    ", сука еберко?",
                    ", тупой мудак?",
                    ", педераст?",
                    ", анальное ебанько?",
                    "? Охуенно жопный вопрос.",
                    "? Пиздец, но вопрос для педерастов.",
                    "? Ебануть тебя моим кортиком!",
                    "? Тельняшку тебе в пизду!",
                    "? Срал я на тебя пушечными ядрами.",
                    "? Для ебаного капитана это хуевый вопрос...",
                    "? В пизду мою пристань...",
                    ", трап те в жопу?",
                    ", тупая ты крыса?",
                    ", палубный пидор?",
                    ", штормовая сучара?",
                    "? Деревянную ногу тебе во влагалище.",
                    "? Шляпу капитана тебе в пиздень!",
                },
                SpecificWords = new string[] {
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                },
                NotAfter = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
            }),
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Exclamation,
                Propability = 128,
                IgnoreWhitespaces = false,
                KillPreviousWhitespace = false,
                RequiresAi = false,
                Templates = new string[] {
                    "! Просто заебись!",
                    "! И вообще, идите вы все на хуй!",
                    "! ВЫР-ВЫР-ВЫР!",
                    "! Охуеть!",
                    "! Обосрись-ка, блядина!",
                    "! Пизда зомбакам!",
                    "! Это просто охуительный пиздец, дорогие мои!",
                    "! Хуяк!",
                    "! Это же просто какой-то штормовой пиздец!",
                    "! Ща насру!",
                    "! Совсем  охуели, пидарасы!",
                    "! Пиздец!",
                    "! Соси хуй, пидор!",
                    "! Бля!",
                    "! Блядь!",
                    "! Ебаный в рот!",
                    "! Хуй!",
                    "! Просто заебись!",
                    "! И вообще, идите вы все на хуй!",
                    "! Охуеть!",
                    "! Это просто охуительный пиздец, дорогие мои!",
                    "! Это же просто какой-то штормовой пиздец!",
                    "! Совсем  охуели, пидарасы!",
                    "! Пиздец!",
                    "! Ебаный в рот!",
                },
                SpecificWords = new string[] {
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                },
                NotAfter = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
            }),
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Dash,
                Propability = 128,
                IgnoreWhitespaces = false,
                KillPreviousWhitespace = false,
                RequiresAi = false,
                Templates = new string[] {
                    "* Еб твою мать! *",
                    "* Ебать твой анус! *",
                },
                SpecificWords = new string[] {
                    "—",
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                },
                NotAfter = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
            }),
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Dot,
                Propability = 128,
                IgnoreWhitespaces = false,
                KillPreviousWhitespace = false,
                RequiresAi = false,
                Templates = new string[] {
                    ". Мда...",
                    ". Пиздец...",
                    ". Хуево...",
                    ". Вот, бля, пиздец то какой наступил...",
                },
                SpecificWords = new string[] {
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                    TokenType.Dot,
                },
                NotAfter = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
            }),
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Unknown,
                Propability = 128,
                IgnoreWhitespaces = false,
                KillPreviousWhitespace = false,
                RequiresAi = false,
                Templates = new string[] {
                    ", зырь, пидарюга:",
                    ", вот те:",
                    ", на, подавись хуем:",
                },
                SpecificWords = new string[] {
                    ":",
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                    TokenType.Whitespace,
                },
                NotAfter = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
            }),
        };


        public IWordBuilder WordBuilder { get; } = new WordBuilder(
            new string[]
            {
                "пидор",
                "муд",
                "хуе",
                "манд",
                "уеб",
                "зл",
                "пизд",
                "говн",
                "перд",
                "ослоеб",
                "говноеб",
                "еб",
                "жоп",
                "выеб",
            },
            new (string, Cases)[]
            {
                ("ас", Cases.Nominative),
                ("ан", Cases.Nominative),
                ("ос", Cases.Nominative),
                ("охуй", Cases.Nominative),
                ("аса", Cases.Genitive),
                ("ана", Cases.Genitive),
                ("оса", Cases.Genitive),
                ("охуя", Cases.Genitive),
                ("асу", Cases.Dative),
                ("ану", Cases.Dative),
                ("осу", Cases.Dative),
                ("охую", Cases.Dative),
                ("аса", Cases.Accusative),
                ("ана", Cases.Accusative),
                ("оса", Cases.Accusative),
                ("охуя", Cases.Accusative),
                ("асом", Cases.Ablative),
                ("аном", Cases.Ablative),
                ("осом", Cases.Ablative),
                ("охуем", Cases.Ablative),
                ("асе", Cases.Prepositional),
                ("ане", Cases.Prepositional),
                ("осе", Cases.Prepositional),
                ("охуе", Cases.Prepositional),
            });

    }
}
    
