using Syphon.Parsing;
using Syphon.Processing;
    
namespace Syphon.Configuration
{
    internal sealed class LudvigRuPreset : IPreset
    {
        public string Id => "ludvig-ru";

        public string Name => "Людвиг Аристархович";

        public string[] Boundaries { get; } = new[]
        {
            " ", 
            "\n    ", 
            ".", 
            ",", 
            "-", 
            "—", 
            ":", 
            "!", 
            "?", 
        };

        public IParser[] Parsers { get; } = new IParser[]
        {
            new Punctuation(new string[] {
            }),
            new Verb(new string[] {
                "(?<end>(ил|ал|ась|ала|ало|али)\\b)", 
                "(?<end>(ат|или|ут|ыл|ыло|ыли|ыла)\\b)", 
                "(?<end>(ать|ить|еть|аться|еться|иться|ул|ил|ал|ула|ала|ила|улся|ился|ался|илась|алась|иться|улась|ило|ало|уло|илось|алось|улось)\\b)", 
            }),
            new Noun(new string[] {
                "(?<end>(ант|ин|ец|да|ер|ка|ок|зь|акт|ис|ор|ик|та|ул|он|ид|ри|уй|инг)\\b)", 
                "(?<end>(ма|чи|ча|че|чь|ну|ын|ына|ыни|ыно|от|ня|ди|ги|ра)\\b)", 
            }),
            new Adjective(new string[] {
                "[^\\b](?<end>(ый|ий|ай|ое|ие|ого|его|их|им|ом|ой|ых|ую|ая|уя)\\b)", 
                "[^\\b](?<end>(ый|ий|ай|ей|ой|ее|его|ого|им|ая|ия|ыя|оя|ому|ыми|ими|ым)\\b)", 
                "[^\\b](?<end>(его|ые|ии|ие)\\b)", 
            }),
            new Preposition(new string[] {
                "(?<end>\\b(и|в|на|от|под|за|как|что|со|или|у|но|из|за|под|к|для|до|после|без|можно|же|по|)\\b)", 
            }),
        };


        public IRule[] Rules { get; } = new IRule[]
        {
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Whitespace,
                Propability = 128,
                IgnoreWhitespaces = true,
                KillPreviousWhitespace = true,
                RequiresAi = false,
                Templates = new string[] {
                    ", ебать я всё хочу, ",
                    ", руку мне в жопу, ",
                    ", хуй мне в пупок, ",
                    ", залупу мне в нос, ",
                    ", отъеберить всех как следует, ",
                    ", еба, ",
                    ", разорвать тебе анус, ",
                    ", якорь мне в жопу, ",
                    ", пиздееееец, ",
                    ", ёпт, ",
                    ", вот бля, ",
                    ", ебана, ",
                    ", пердануть тебе в нос, ",
                    ", насрать тебе в ухо, ",
                    ", зашить твой анус, ",
                    ", ебать вас в жопу, ",
                    ", просто злоебенище, ",
                    ", уебаться просто, ",
                    ", еба, ",
                    ", дремучая пиздень, ",
                    ", вот говно, ",
                    ", срать на всех, ",
                    ", обдристаться можно, ",
                    ", ебать-копать, ",
                    ", фак мой моск, ",
                    ", вротмненоги, ",
                    ", блядь, ",
                    ", нахуй, ",
                    ", ебанаврот, ",
                    ", в жопу, ",
                    " - и это просто пиздец - долбоёбство просто - ",
                    " - уебанство - ",
                    " - иметь тебя в рот и в жопу - ",
                    " - разъеберище полное - ",
                    " - отпиздить всех нахуй - ",
                    " - ссать и срать - ",
                    " - и разъебись оно всё к чертям сучьим - ",
                    " - ебаный конём в рот и в жопу - ",
                    " - вот еба - ",
                    " - усраться просто - ",
                    " - отлижите клитор или отсосите хуй, неважно - ",
                    " - а обычно пиздец быстро приходит - ",
                    " - жопа поглотит вас - ",
                    " - наступает пиздец - ",
                    " - разъебенить всё - ",
                    " - ух, ядрёная была ебля - ",
                    " - насрать мне на рыло - ",
                    " - разодрать вам пизду - ",
                    " - лизать мою мошонку - ",
                    " - ебать ваши яйца - ",
                    " - драть вас в жопу - ",
                    " - лизать моё шоколадное очко - ",
                    " - вот тут полный пиздец - ",
                    " - и как же тут не охуеть - ",
                    " - драть вас шваброй в жопу - ",
                    " - но это ж пиздец! - ",
                    " - и кто бы блядь подумал - ",
                    " - ебать его в рот - ",
                    ", ебалайка сучья, ",
                    ", трахать вас и спереди и сзади, ",
                    ", въебать бы тебя в стену, ",
                    ", ебать-колотить, ",
                    ", отпиздить всех нах, ",
                    ", лизать моё очко, ",
                    ", сосать мой хуй, ",
                    ", нюхни моего пердежа, ",
                    ", выпей-ка моих ссак, ",
                    ", сожри кучу говна, ",
                    ", намазать тебе хуй ядом, ",
                    ", нассать на лоб тебе, ",
                    ", ебать тебя во все отверстия, ",
                    ", и это бздунство, ",
                    ", блядина, ",
                    ", пидарас, ",
                    ", бздеть на всё, ",
                    ", ебать сто коров, ",
                    ", охуеть просто, ",
                    ", охуенно просто, ",
                    ", ебанавт, ",
                    ", ебать вас всех, ",
                    ", оттолкать говно в жопе, ",
                    ", срать я хотел на всё, ",
                    ", обоссаться просто, ",
                    ", обоссаный валенок, ",
                    ", ебучая пиздопроёбина, ",
                    ", продраная жопа, ",
                    ", ебать вас в анус, ",
                    ", рвать тебе целку, ",
                    ", сучий мудозвон, ",
                    ", сука ебаная, ",
                    ", сучий потрох, ",
                    ", обдрочиться просто, ",
                    ", срать тебе в рот, ",
                    ", бля, ",
                    ", ебаный в рот, ",
                    ", обосраться, ",
                    ", охуеть можно, ",
                    ", и хватит тут блядовать, ",
                    ", и это пиздец блядство, ",
                    ", впиздячить те по уши, ",
                    ", дуроёб, ",
                    ", ебическая сила, ",
                    ", коноёб, ",
                    ", однохуйственно, ",
                    ", пизда малосольная, ",
                    ", пиздун, ",
                    ", хуеглот, ",
                    ", хуё-моё, ",
                    ", шобла-ёбла, ",
                },
                SpecificWords = new string[] {
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                    TokenType.Noun,
                    TokenType.Verb,
                    TokenType.Adjective,
                },
                NotAfter = new TokenType[] {
                },
            }),
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Dot,
                Propability = 64,
                IgnoreWhitespaces = false,
                KillPreviousWhitespace = false,
                RequiresAi = false,
                Templates = new string[] {
                    ". В общем, отсосите-ка хуй!",
                    ". Короче, мудоёбщина полная!",
                    ". И срать на всё это!",
                    ". К слову, пойду-ка я посру...",
                    ". А вы хоть раз засовывали палец в жопу?",
                    ". Но это всё хуйня!",
                    ". Блядь, вот кто бы мог подумать!",
                    ". Это ж охуеть можно!",
                    ". Да ебать нахуй!",
                    ". Пидоры, что ж с них взять!",
                },
                SpecificWords = new string[] {
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                },
                NotAfter = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
            }),
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Question,
                Propability = 128,
                IgnoreWhitespaces = false,
                KillPreviousWhitespace = false,
                RequiresAi = false,
                Templates = new string[] {
                    "? Ебаааать вас всех!",
                    "? Вылижите мои шоколадные яйца.",
                    "? А вообще, мне срать.",
                    "? Уебанский вопрос...",
                    "? Как же ответят на этот вопрос долбоёбы?",
                    "? Кстати, есть чё?",
                    ", мудоёб?",
                    ", мудак?",
                    ", пидор?",
                    ", еба?",
                    "? Охуенно сложный вопрос.",
                    "? Пиздец, вопрос нерешаем.",
                },
                SpecificWords = new string[] {
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                },
                NotAfter = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
            }),
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Whitespace,
                Propability = 128,
                IgnoreWhitespaces = true,
                KillPreviousWhitespace = true,
                RequiresAi = true,
                Templates = new string[] {
                    ", {noun:Accusative} мне в {noun:Accusative}, ",
                    ", {noun:Accusative} мне в нос, ",
                    ", разорвать тебе {noun:Accusative}, ",
                    ", {noun:Accusative} мне в жопу, ",
                    ", {noun}, ",
                    ", вот {noun}, ",
                    ", пердануть тебе в {noun:Accusative}, ",
                    ", насрать тебе в {noun:Accusative}, ",
                    ", ебать вас в {noun:Accusative}, ",
                    ", дремучий {noun}, ",
                    ", вот {noun}, ",
                    ", фак мой {noun}, ",
                    " - и это просто {noun} - долбоёбство просто - ",
                    " - иметь тебя в {noun:Accusative} и в {noun:Accusative} - ",
                    " - ебаный конём в {noun:Accusative(1)} и в {noun:Accusative(1)} - ",
                    " - {noun} поглотит вас - ",
                    " - наступает {noun} - ",
                    " - насрать мне на {noun:Accusative} - ",
                    " - разодрать вам {noun:Accusative} - ",
                    " - драть вас в {noun:Accusative} - ",
                    " - вот тут полный {noun} - ",
                    " - драть вас шваброй в {noun:Accusative} - ",
                    " - но это ж {noun(1)}! - ",
                    ", намазать тебе {noun} ядом, ",
                    ", нассать на {noun:Accusative} тебе, ",
                    ", ебать тебя во все отверстия, ",
                    ", обоссаный {noun}, ",
                    ", ебать вас в {noun:Accusative}, ",
                    ", рвать тебе {noun:Accusative}, ",
                    ", сучий {noun}, ",
                    ", сучий {noun(1)}, ",
                },
                SpecificWords = new string[] {
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                    TokenType.Noun,
                    TokenType.Verb,
                    TokenType.Adjective,
                },
                NotAfter = new TokenType[] {
                },
            }),
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Dot,
                Propability = 64,
                IgnoreWhitespaces = false,
                KillPreviousWhitespace = false,
                RequiresAi = true,
                Templates = new string[] {
                    ". В общем, отсосите-ка хуй!",
                    ". Короче, мудоёбщина полная!",
                    ". И срать на всё это!",
                    ". К слову, пойду-ка я посру...",
                    ". А вы хоть раз засовывали палец в жопу?",
                    ". Но это всё хуйня!",
                    ". Блядь, вот кто бы мог подумать!",
                    ". Это ж охуеть можно!",
                    ". Да ебать нахуй!",
                    ". Пидоры, что ж с них взять!",
                },
                SpecificWords = new string[] {
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                },
                NotAfter = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
            }),
            new DefaultRule(new RuleDefinition
            {
                AcceptType = TokenType.Question,
                Propability = 128,
                IgnoreWhitespaces = false,
                KillPreviousWhitespace = false,
                RequiresAi = false,
                Templates = new string[] {
                    "? Ебаааать вас всех!",
                    "? Вылижите мои шоколадные яйца.",
                    "? А вообще, мне срать.",
                    "? Уебанский вопрос...",
                    "? Как же ответят на этот вопрос долбоёбы?",
                    "? Кстати, есть чё?",
                    ", мудоёб?",
                    ", мудак?",
                    ", пидор?",
                    ", еба?",
                    "? Охуенно сложный вопрос.",
                    "? Пиздец, вопрос нерешаем.",
                },
                SpecificWords = new string[] {
                },
                Before = new TokenType[] {
                },
                NotBefore = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Dot,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Question,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
                After = new TokenType[] {
                },
                NotAfter = new TokenType[] {
                    TokenType.Comma,
                    TokenType.Quote,
                    TokenType.Colon,
                    TokenType.Exclamation,
                    TokenType.Dash,
                    TokenType.OpeningBrace,
                    TokenType.ClosingBrace,
                },
            }),
        };


        public IWordBuilder WordBuilder { get; } = new WordBuilder(
            new string[]
            {
                "пидор",
                "муд",
                "хуе",
                "манд",
                "уеб",
                "зл",
                "пизд",
                "говн",
                "перд",
                "ослоеб",
                "говноеб",
                "еб",
                "жоп",
                "выеб",
            },
            new (string, Cases)[]
            {
                ("ас", Cases.Nominative),
                ("ан", Cases.Nominative),
                ("ос", Cases.Nominative),
                ("охуй", Cases.Nominative),
                ("ец", Cases.Nominative),
                ("аса", Cases.Genitive),
                ("ана", Cases.Genitive),
                ("оса", Cases.Genitive),
                ("охуя", Cases.Genitive),
                ("еца", Cases.Nominative),
                ("асу", Cases.Dative),
                ("ану", Cases.Dative),
                ("осу", Cases.Dative),
                ("охую", Cases.Dative),
                ("ецу", Cases.Nominative),
                ("аса", Cases.Accusative),
                ("ана", Cases.Accusative),
                ("оса", Cases.Accusative),
                ("охуя", Cases.Accusative),
                ("еца", Cases.Nominative),
                ("асом", Cases.Ablative),
                ("аном", Cases.Ablative),
                ("осом", Cases.Ablative),
                ("охуем", Cases.Ablative),
                ("ецом", Cases.Nominative),
                ("асе", Cases.Prepositional),
                ("ане", Cases.Prepositional),
                ("осе", Cases.Prepositional),
                ("охуе", Cases.Prepositional),
                ("еце", Cases.Nominative),
            });

    }
}
    
